---
title: "Overall procedure for analyzing nectar experiments"
author: "Bill Langford"
date: "18/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Might also want to link some of these things to screen grab videos where I have them.

#  Startup

## Make sure all libraries are committed and pushed to github.

```
Especially the project.yaml file...
```

## Start nectar machines from image snapshot.

```
blah blah blah
```

## Schedule tzar runs.

```
java    -Djavax.net.ssl.trustStorePassword=changeit    -jar    $TZAR_JAR    scheduleruns    https://github.com/langfob/btzar.git    --repotype=GIT    --clustername=bdpg     --runset=someNormalRuns
```

## Start tzar pollandrun on nectar machines.

```
java    -Djavax.net.ssl.trustStorePassword=changeit    -jar   $TZAR_JAR    pollandrun    --repository-prefixes=https://github.com/langfob/btzar.git    --scpoutputhost=glass.eres.rmit.edu.au    --scpoutputuser=rdv    --finaloutputpath=/home/rdv/tzar_output/bdpg_nectar/ExpOutput    --clustername=bdpg    --runset=someNormalRuns
```

#  Monitoring running experiments

## View runset records in pgadmin.

```
blah blah blah
```

#  Rerunning experiments where necessary.

Some runs fail due to lack of memory on the small nectar machine, so you need to rerun them on larger machines using the same random seed to get the same run.

## Find out which (if any) runs failed and why.

Tzar is not always marking failed runs as failed, so you need to search each run's directory and log file for indications of failure.   

- One sign of failure is not having enough output subdirectories.
    - *** NOTE that the countFiles.sh script is currently very specific to the case where you're running 6 variants and the directory names all have a number followed by "default_scenario".  Need to add some arguments to that script to make it more generic.
```
export RUNSET_OUT_DIR="~/tzar_output/bdpg_nectar/ExpGen6basicVariants/Batch_1_500"   #  for exammple...
cd $RUNSET_OUT_DIR
~/tzar_output/bdpg_nectar/ShellScripts/countFiles.sh
```
- Another sign of failure is when the log file contains various words that are output when different kinds of crashes occur, e.g., "trycatch", "quit", or "traceback".
    - Note that these greps take a fairly long time to run over 500 directories.
```
cd $RUNSET_OUT_DIR
grep "tryCatch" 2????_default_scenario/metadata/logging.log
grep "quit" 2????_default_scenario/metadata/logging.log
grep "traceback" 2????_default_scenario/metadata/logging.log
```
- A sign of success is when the log file ends with "ALL DONE", so one sanity check when none of the greps above return anything is to grep for "ALL DONE".
```
cd $RUNSET_OUT_DIR
#grep "ALL DONE" 2????_default_scenario/metadata/logging.log
grep "ALL DONE" 2????_default_scenario/metadata/logging.log | wc
```

## Move all failed runs to a separate directory

```
cd $RUNSET_OUT_DIR
mkdir ~/tzar_output/bdpg_nectar/ExpGen6basicVariants_failedRuns/Batch_1_500_failed
    #  Run this for each failed run XXXXX found above.
mv XXXXX_default_scenario FailedRuns
```

## Collect random seeds for runs to be rerun

```
cd ~/tzar_output/bdpg_nectar/ExpGen6basicVariants_failedRuns/Batch_1_500_failed
grep -n "new rand_seed = " ?????_default_scenario/metadata/logging.log
#grep -n forced_seed 22311_default_scenario/metadata/logging.log
```

## Add random seeds for reruns in project.yaml.

```
    get_full_run_rand_seed_from_yaml_array: TRUE
    rand_seed_yaml_array:
        - 775280952 
        - 1380332469 
        - 1572892665 
        - 381123065 
        - 1028866767 
        - 1705774307 
        - 1212330818 
...
repetitions:
    generators:
#        - key: cur_run_idx
        - key: cur_rand_seed_idx
          generator_type: linear_step
          start: 1
          step_size: 1
          count: 7
```

## Commit and push reruns

```
blah blah blah
```

## Schedule any necessary reruns

Large machines may already be running in tzar pollandrun mode to pick them up, so you may not need to do anything to pick them up.

```
java    -Djavax.net.ssl.trustStorePassword=changeit    -jar    $TZAR_JAR    scheduleruns    https://github.com/langfob/btzar.git    --repotype=GIT    --clustername=bdpg     --runset=previousFails
```

## Start pollandrun if necessary

Large machines may already be running in tzar pollandrun mode to pick them up, so you may not need to do anything to pick them up.  If you do though, here's an example command.    

Note that you want the runset name in this tzar command and the one above to match if you're trying to get the machines with this pollandrun command to only pick up runs from this runset.  This could be the case if you're still running normal runs on small machines and only want the small machines to pick up those runs while only the large machines pick up these reruns.  It doesn't matter what the runset name is so long as it matches in both commands.

```
java    -Djavax.net.ssl.trustStorePassword=changeit    -jar   $TZAR_JAR    pollandrun    --repository-prefixes=https://github.com/langfob/btzar.git    --scpoutputhost=glass.eres.rmit.edu.au    --scpoutputuser=rdv    --finaloutputpath=/home/rdv/tzar_output/bdpg_nectar/ExpRerunsOfPreviousFails    --clustername=bdpg    --runset=previousFails
```

## Monitor reruns to be sure they're working.

Problems with running large machines from more than one nectar allocation due to failed connection to gurobi license server.  

Run pgadmin and check the last n rows of the "runs" table in the View Data menu entry.

```
blah blah blah
```

## Aggregate results by reserve selector

Move to glass and run the script that produces a csv file for each reserve selector.

```
blah blah blah
```

## Move the aggregated files to the mac for analysis

zip the result csv files and scp the zip file to the mac.

```
blah blah blah
```

## Clean the aggregated data

Load the csv file and examine and clean it using the R notebook: cleanBdpgEasyHardData.Rmd

```
blah blah blah
```

## Analyze the results

Load the csv file into: cleanBdpgEasyHardData.Rmd

```
blah blah blah
```







